languageCode = "en-us"
title = "Nick Turman-Bryant"
baseurl = "https://bryantnick.github.io"
theme = "prologue"
publishDir = "../bryantnick.github.io"

[params]
  name = "Nick Turman-Bryant"
  description = "Data Analyst and Research Engineer"
  copyright = "2017"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

  [[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/nickturmanbryant/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/ntbryant"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "nicktb@pdx.edu"

# Portfolio column one

[[params.portfolio1]]
  title = "Ipsum Feugiat"
  alt = ""
  source = "#"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "#"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "#"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "#"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "#"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "#"
  url = "#"
