languageCode = "en-us"
title = "Nick Turman-Bryant"
baseurl = "https://ntbryant.github.io"
theme = "prologue"
publishDir = "../ntbryant.github.io"

[params]
  name = "Nick Turman-Bryant"
  description = "Data Analyst and Research Engineer"
  copyright = "2017"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/nickturmanbryant/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/ntbryant"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/nickturmanbryant/"

# Portfolio column one

[[params.portfolio1]]
  title = "Ethiopia Mapping"
  alt = ""
  source = "#"
  url = "https://nicktb.shinyapps.io/AfarStudy/"

# Portfolio column two

[[params.portfolio2]]
  title = "Kenya Sanitation"
  alt = ""
  source = "#"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Kenya Solar"
  alt = ""
  source = "#"
  url = "#"
